### ISSUE TITLE
Log "no points" as info or debug

### ISSUE THREAD

**Issue by edenhaus** [Danielhiversen/home_assistant_tractive#12]
Hi Daniel,

https://github.com/Danielhiversen/home_assistant_tractive/blob/4424113433d035bab6bf75447c4c3e0ab716b642/custom_components/tractive/device_tracker.py#L202

I would suggest to log "No points" not as error, but maybe as info or even as debug. You are getting only the points of the last 6 hours and if my dog is not leaving the house the whole day (for example on a rainy day) the tracker will not update his position. The reason is probably that the gps is very inaccurate in the house (we have big walls) and therefore the tracker will not update his position.
Reducing the log level will also help on issues like #11 and for my opinion no points is a valid and therefore logging as error is wrong.

Cheers,
Robert

**Comment by Danielhiversen** [comment]
Agree.
Please open a pull request to change it.
