### ISSUE TITLE
Device tracker not showing up

### ISSUE THREAD

**Issue by tebulrich** [Danielhiversen/home_assistant_tractive#19]
Installed yesterday via HACS. Confirmed that files are in custom components folder, doublechecked login data (could login on tractive website), but device tracker doesnt show up. Also checked error log, but nothing.

**Comment by Danielhiversen** [comment]
Could you enable debug logging for the tractive component?

**Comment by tebulrich** [comment]
> 
> 
> Could you enable debug logging for the tractive component?

how do i do that?

**Comment by Danielhiversen** [comment]
https://www.home-assistant.io/integrations/logger/

**Comment by tebulrich** [comment]
Problem fixed. I didnt have the GPS on for a long time and so it didnt "create" the tracker. Turned it on for 10 minutes and then it worked.
