### ISSUE TITLE
Gps accuracy 0

### ISSUE THREAD

**Issue by unosakk** [Danielhiversen/home_assistant_tractive#20]
Gps accuracy always shows 0. 
There is a attribute "pos_uncertainty" that changes values. 

Could "pos_uncertainty" value be pushed to "Gps accuracy" or is there a point to having these values seperate?

![image](https://user-images.githubusercontent.com/67309358/102233632-24cb1580-3ef9-11eb-8b6a-8fb7c8d58fc1.png)

**Comment by Danielhiversen** [comment]
I recommend to start using the official integration https://www.home-assistant.io/integrations/tractive/
