### ISSUE TITLE
Location not updated

### ISSUE THREAD

**Issue by jvanesch** [Danielhiversen/home_assistant_tractive#22]
Tractive location doesn't get updated correctly (not at all) in Home Assistant. No error code, refresh active.. there is a connection with API active. The "away status" only set when tracker is not available/connected. Location information seems not to be used to set the status when tracker is really "away".

<img width="394" alt="Screenshot 2021-02-05 at 13 10 41" src="https://user-images.githubusercontent.com/20064478/107032125-99148d80-67b3-11eb-8b10-dd4ab9315370.png">

**Comment by Danielhiversen** [comment]
Is the latitude / longitude updated correctly?

**Comment by jvanesch** [comment]
> Is the latitude / longitude updated correctly?

The tractive app shows the correct latitude / longitude. I will check if this is transferred and will let you know.
What will trigger the update frequency? sometimes the latest status in HA is a few hours old but up-to-date in the tractive app.

**Comment by jvanesch** [comment]
@Danielhiversen I did check it, it's not getting updated... only when there is no latitude / longitude available when the the tracker is turned off or having no gps signal. any idea?

**Comment by Danielhiversen** [comment]
I recommend to start using the official integration https://www.home-assistant.io/integrations/tractive/
