### ISSUE TITLE
Tracker Infos not present after restart

### ISSUE THREAD

**Issue by EpicLPer** [Danielhiversen/home_assistant_tractive#25]
After restarting Hass the Tracker Infos are not immediately available which throws off any custom sensor built around it.

In this case every stat below is missing, such as `battery_level` which I've built a custom template/sensor for to display on Lovelace as a separate entry. That sensor however doesn't show up now due to not being present.

If it helps: My tracker battery died and is now charging, so the tracker isn't actually online right now. Maybe this can be cached somehow if that's the case it failed?

![image](https://user-images.githubusercontent.com/8442196/110542647-9cd85e80-8129-11eb-8786-348f1078c404.png)

**Comment by Danielhiversen** [comment]
> not immediately available
How long does it take before it is available?

**Comment by EpicLPer** [comment]
When the tracker is actively online the info updates immediately it seems. I'll try it once I'm charging my tracker later on. It seems to only update/create those entries when it's actively on.

**Comment by Danielhiversen** [comment]
It only fetches the last 6 hours of data

**Comment by EpicLPer** [comment]
Hm, but can't those values be cached so a reboot doesn't fully flush everything and makes custom sensors Error out? Or, if no info is available, fetch further back?

**Comment by Danielhiversen** [comment]
It is possible to add, but someone has to do it :)

**Comment by Danielhiversen** [comment]
I recommend to start using the official integration https://www.home-assistant.io/integrations/tractive/
