### ISSUE TITLE
Update positions... 

### ISSUE THREAD

**Issue by Snille** [Danielhiversen/home_assistant_tractive#4]
Hi, thank you for this integration! :)
It works, but only update the GPS positions of the cats then I restart HA.
Is there a parameter in the config I have to set to get more frequent position updates?

**Comment by tru01** [comment]
Looking forward for this :-) 
Same problem here

**Comment by Danielhiversen** [comment]
Unfortunately, I do not have any device to test with at the moment.
I think I found the bug, so it would be great if you would test the latest version.

**Comment by Snille** [comment]
Hi! I have installed via HACS, so, how do I test the latest version? :) Do you release it through HACS, and we (I) can update and test it?

**Comment by Danielhiversen** [comment]
You can update to the latest version on master from hacs

**Comment by Snille** [comment]
I only get 0.1 via hacks... Is that correct?

**Comment by Danielhiversen** [comment]
No, choose reinstall and select `master` version

**Comment by Snille** [comment]
I think I've done it. :) How often should it update the positions? It's been one hour now, for both my cat trackers. :)

**Comment by Danielhiversen** [comment]
It should fetch the latest position every 2 minutes. And show the same position as you see on https://my.tractive.com/#/

**Comment by Snille** [comment]
Hmm... The "coordinates" updates now, but the "time" is not (on the object). The time "data" updates... :)

**Comment by Snille** [comment]
The green ones updates.... (I'm guessing all data updates). The red does not. :)
![image](https://user-images.githubusercontent.com/1011699/96179623-7115cb80-0f31-11eb-85a0-1d3c39ca979b.png)

**Comment by Danielhiversen** [comment]
Last updated is for the state: Home /not home

**Comment by Snille** [comment]
Ok, I'm not sure what that menas. :) But it looks like it's working with the data at least, it updates. The state never seam to change, even if the cat's are not home... :)

**Comment by Danielhiversen** [comment]
Does it work for you now?

**Comment by Snille** [comment]
Depends on what you mean. :) The data updates on the device (time, positions and so on). But the tracker is always "home" even if the tracker is not in the "home" zone.

**Comment by Danielhiversen** [comment]
Do you use the latest version?
Is the longitude and latitude updated correctly?

**Comment by Snille** [comment]
I'm on 0.2 if I look under "Information" and yes I believe the coordinates are updating. The "circle" is moving around on the map (every second minute or so) as well. :)

**Comment by Danielhiversen** [comment]
Not able to reproduce this.
The home/not home state is sat by home assistant core, not this component.
So if the location is correct, I do not think it is anything I can do with this.
